/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TraineeRouteImport } from './routes/trainee'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as TraineeIndexRouteImport } from './routes/trainee.index'
import { Route as TraineeProgressRouteImport } from './routes/trainee.progress'
import { Route as TraineeResourcesRouteImport } from './routes/trainee.resources'
import { Route as TraineeCoursesIndexRouteImport } from './routes/trainee.courses.index'
import { Route as TraineeCoursesCourseIdRouteImport } from './routes/trainee.courses.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeRoute = TraineeRouteImport.update({
  id: '/trainee',
  path: '/trainee',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const TraineeIndexRoute = TraineeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TraineeRoute,
} as any)
const TraineeProgressRoute = TraineeProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TraineeRoute,
} as any)
const TraineeResourcesRoute = TraineeResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => TraineeRoute,
} as any)
const TraineeCoursesIndexRoute = TraineeCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => TraineeRoute,
} as any)
const TraineeCoursesCourseIdRoute = TraineeCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => TraineeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/trainee': typeof TraineeRouteWithChildren
  '/trainer': typeof TrainerRoute
  '/trainee/progress': typeof TraineeProgressRoute
  '/trainee/resources': typeof TraineeResourcesRoute
  '/trainee/': typeof TraineeIndexRoute
  '/trainee/courses/$courseId': typeof TraineeCoursesCourseIdRoute
  '/trainee/courses/': typeof TraineeCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/trainer': typeof TrainerRoute
  '/trainee/progress': typeof TraineeProgressRoute
  '/trainee/resources': typeof TraineeResourcesRoute
  '/trainee': typeof TraineeIndexRoute
  '/trainee/courses/$courseId': typeof TraineeCoursesCourseIdRoute
  '/trainee/courses': typeof TraineeCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/trainee': typeof TraineeRouteWithChildren
  '/trainer': typeof TrainerRoute
  '/trainee/progress': typeof TraineeProgressRoute
  '/trainee/resources': typeof TraineeResourcesRoute
  '/trainee/': typeof TraineeIndexRoute
  '/trainee/courses/$courseId': typeof TraineeCoursesCourseIdRoute
  '/trainee/courses/': typeof TraineeCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/trainee'
    | '/trainer'
    | '/trainee/progress'
    | '/trainee/resources'
    | '/trainee/'
    | '/trainee/courses/$courseId'
    | '/trainee/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/trainer'
    | '/trainee/progress'
    | '/trainee/resources'
    | '/trainee'
    | '/trainee/courses/$courseId'
    | '/trainee/courses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/trainee'
    | '/trainer'
    | '/trainee/progress'
    | '/trainee/resources'
    | '/trainee/'
    | '/trainee/courses/$courseId'
    | '/trainee/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  TraineeRoute: typeof TraineeRouteWithChildren
  TrainerRoute: typeof TrainerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee': {
      id: '/trainee'
      path: '/trainee'
      fullPath: '/trainee'
      preLoaderRoute: typeof TraineeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainee/': {
      id: '/trainee/'
      path: '/'
      fullPath: '/trainee/'
      preLoaderRoute: typeof TraineeIndexRouteImport
      parentRoute: typeof TraineeRoute
    }
    '/trainee/progress': {
      id: '/trainee/progress'
      path: '/progress'
      fullPath: '/trainee/progress'
      preLoaderRoute: typeof TraineeProgressRouteImport
      parentRoute: typeof TraineeRoute
    }
    '/trainee/resources': {
      id: '/trainee/resources'
      path: '/resources'
      fullPath: '/trainee/resources'
      preLoaderRoute: typeof TraineeResourcesRouteImport
      parentRoute: typeof TraineeRoute
    }
    '/trainee/courses/': {
      id: '/trainee/courses/'
      path: '/courses'
      fullPath: '/trainee/courses/'
      preLoaderRoute: typeof TraineeCoursesIndexRouteImport
      parentRoute: typeof TraineeRoute
    }
    '/trainee/courses/$courseId': {
      id: '/trainee/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/trainee/courses/$courseId'
      preLoaderRoute: typeof TraineeCoursesCourseIdRouteImport
      parentRoute: typeof TraineeRoute
    }
  }
}

interface TraineeRouteChildren {
  TraineeProgressRoute: typeof TraineeProgressRoute
  TraineeResourcesRoute: typeof TraineeResourcesRoute
  TraineeIndexRoute: typeof TraineeIndexRoute
  TraineeCoursesCourseIdRoute: typeof TraineeCoursesCourseIdRoute
  TraineeCoursesIndexRoute: typeof TraineeCoursesIndexRoute
}

const TraineeRouteChildren: TraineeRouteChildren = {
  TraineeProgressRoute: TraineeProgressRoute,
  TraineeResourcesRoute: TraineeResourcesRoute,
  TraineeIndexRoute: TraineeIndexRoute,
  TraineeCoursesCourseIdRoute: TraineeCoursesCourseIdRoute,
  TraineeCoursesIndexRoute: TraineeCoursesIndexRoute,
}

const TraineeRouteWithChildren =
  TraineeRoute._addFileChildren(TraineeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  TraineeRoute: TraineeRouteWithChildren,
  TrainerRoute: TrainerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
